### ISSUE TITLE
Remove ruby-gcj

### ISSUE THREAD

**Issue by hsivonen** [validator/htmlparser#16]
I believe gcj itself has been discontinued and that Venus has migrated to Gumbo.

**Comment by hsivonen** [comment]
@rubys, is the above correct, and is it OK to remove the `ruby-gcj` directory?

**Comment by sideshowbarker** [comment]
Fixed by https://github.com/validator/htmlparser/commit/e5e552fb910d79aa70cfa78115454d06979d0173
