### ISSUE TITLE
Help wanted: review Maven pom.xml changes for test automation

### ISSUE THREAD

**Issue by sideshowbarker** [validator/htmlparser#45]
PR #44 includes a change to the Maven `pom.xml` file to enable automated testing of the html5lib-tests suite. See 2fbcd75.

This issue is a request for review of that change by anyone with domain expertise/experience with Maven — in particular, with the AntRun plugin.

You’ll notice the `pom.xml` invokes the AntRun `javac` and `java` targets with `fork=true`. There are comments in the change which explain why, but ideally, it seems preferable to make it work without needing `fork=true`. So any insights into how that might be possible would be welcome.

@anthonyvdotbe and @carlosame — your reviews would be especially welcome.

**Comment by carlosame** [comment]
> the `pom.xml` invokes the AntRun `javac` and `java` targets with `fork=true`.

With which JDK version are you running the tests?

**Comment by carlosame** [comment]
> With which JDK version are you running the tests?

Nevermind, I see the `[8, 11, 14]`. It is unclear what the outcome with 11 and 14 is going to be once the project is modularized, and the `fork` could make things a bit more 'interesting' in that case.

Is the `fork` also necessary with JDK 11 and 14?

**Comment by sideshowbarker** [comment]
> Is the `fork` also necessary with JDK 11 and 14?

I don’t know. It might not be. I can test.

The reason I don’t know yet is that apparently when you have series of jobs to run in GitHub Actions, and the first couple of jobs fail, the remaining jobs get canceled.

So to test whether we’d have the same problem without `fork` under JDK 11 and 14, maybe I just need to change the config to have `[11, 14, 8]` (to make the Java 8 jobs run last).

**Comment by anthonyvdotbe** [comment]
My advice would be to use "the Maven way", i.e. adapt the tests such that the [Surefire plugin](https://maven.apache.org/surefire/maven-surefire-plugin/index.html) can run them (it's possible to do so without adopting a test framework, as explained [here](https://maven.apache.org/surefire/maven-surefire-plugin/examples/pojo-test.html)).
